In [2]:
import pandas as pd

# Crear datos de solicitudes de préstamo
datos_prestamos = {
    "Cliente": [
        "Carlos", "María", "José", "Ana", "Luis",
        "Sofía", "Pedro", "Elena", "Miguel", "Laura"
    ],
    "MontoSolicitado": [
        45000, 75000, 30000, 90000, 50000,
        120000, 25000, 65000, 40000, 85000
    ],
    "PlazoMeses": [
        12, 24, 6, 36, 18,
        48, 12, 24, 6, 36
    ],
    "IngresoMensual": [
        18000, 32000, 15000, 45000, 22000,
        60000, 14000, 28000, 17000, 38000
    ],
    "EstadoSolicitud": [
        "Aprobado", "Aprobado", "Rechazado", "Aprobado", "Pendiente",
        "Aprobado", "Rechazado", "Pendiente", "Rechazado", "Aprobado"
    ]
}

# Convertir el diccionario en un DataFrame
prestamos = pd.DataFrame(datos_prestamos)

print("DataFrame de solicitudes de préstamo:")
display(prestamos)

# Calcular monto promedio solicitado
monto_promedio = prestamos["MontoSolicitado"].mean()
print("Monto promedio solicitado:", monto_promedio)

# Contar solicitudes por estado
solicitudes_por_estado = prestamos["EstadoSolicitud"].value_counts()
print("\nSolicitudes por estado:")
print(solicitudes_por_estado)

# Mostrar únicamente préstamos aprobados
prestamos_aprobados = prestamos[prestamos["EstadoSolicitud"] == "Aprobado"]
print("\nPréstamos aprobados:")
display(prestamos_aprobados)

# Mostrar clientes con monto solicitado mayor a 50,000
clientes_mayor_50000 = prestamos[prestamos["MontoSolicitado"] > 50000]
print("\nClientes con monto solicitado mayor a 50,000:")
display(clientes_mayor_50000)

# Agrupar por estado y calcular promedio del monto solicitado
promedio_por_estado = prestamos.groupby("EstadoSolicitud")["MontoSolicitado"].mean()
print("\nPromedio del monto solicitado por estado:")
print(promedio_por_estado)

DataFrame de solicitudes de préstamo:

  Cliente  MontoSolicitado  PlazoMeses  IngresoMensual EstadoSolicitud
0  Carlos            45000          12           18000        Aprobado
1   María            75000          24           32000        Aprobado
2    José            30000           6           15000       Rechazado
3     Ana            90000          36           45000        Aprobado
4    Luis            50000          18           22000       Pendiente
5   Sofía           120000          48           60000        Aprobado
6   Pedro            25000          12           14000       Rechazado
7   Elena            65000          24           28000       Pendiente
8  Miguel            40000           6           17000       Rechazado
9   Laura            85000          36           38000        Aprobado

Monto promedio solicitado: 62500.0

Solicitudes por estado:
EstadoSolicitud
Aprobado     5
Rechazado    3
Pendiente    2
Name: count, dtype: int64

Préstamos aprobados:

  Cliente  MontoSolicitado  PlazoMeses  IngresoMensual EstadoSolicitud
0  Carlos            45000          12           18000        Aprobado
1   María            75000          24           32000        Aprobado
3     Ana            90000          36           45000        Aprobado
5   Sofía           120000          48           60000        Aprobado
9   Laura            85000          36           38000        Aprobado

Clientes con monto solicitado mayor a 50,000:

  Cliente  MontoSolicitado  PlazoMeses  IngresoMensual EstadoSolicitud
1   María            75000          24           32000        Aprobado
3     Ana            90000          36           45000        Aprobado
5   Sofía           120000          48           60000        Aprobado
7   Elena            65000          24           28000       Pendiente
9   Laura            85000          36           38000        Aprobado

Promedio del monto solicitado por estado:
EstadoSolicitud
Aprobado     83000.000000
Pendiente    57500.000000
Rechazado    31666.666667
Name: MontoSolicitado, dtype: float64

En este ejercicio se creó un DataFrame llamado prestamos usando un diccionario llamado datos_prestamos. 
Cada clave del diccionario representa una columna, por ejemplo Cliente, MontoSolicitado, PlazoMeses, IngresoMensual y EstadoSolicitud.

La variable prestamos guarda la tabla completa creada con pd.DataFrame(). 
La variable monto_promedio guarda el promedio de la columna MontoSolicitado usando el método mean(). 
La variable solicitudes_por_estado cuenta cuántas solicitudes hay por cada estado usando value_counts(). 
La variable prestamos_aprobados filtra únicamente las filas donde EstadoSolicitud es igual a "Aprobado". 
La variable clientes_mayor_50000 filtra los clientes cuyo MontoSolicitado es mayor a 50000. 
Finalmente, groupby() agrupa los datos por EstadoSolicitud y mean() calcula el promedio del monto solicitado para cada grupo.